//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lotto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Bet_Out
    {
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public string Name { get; set; }
        public string SendToUsername { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
