//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lotto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int ID { get; set; }
        public Nullable<int> UID { get; set; }
        public string three_up { get; set; }
        public string three_ood { get; set; }
        public string three_down { get; set; }
        public string two_up { get; set; }
        public string two_ood { get; set; }
        public string two_down { get; set; }
        public string up { get; set; }
        public string down { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string first_three { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
