//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lotto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ltfomEntities : DbContext
    {
        public ltfomEntities()
            : base("name=ltfomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<Lotto> Lottoes { get; set; }
        public virtual DbSet<Main_Discount> Main_Discount { get; set; }
        public virtual DbSet<Main_Rate> Main_Rate { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<Poll> Polls { get; set; }
        public virtual DbSet<Rate> Rates { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Account_Role> Account_Role { get; set; }
        public virtual DbSet<LottoSub> LottoSubs { get; set; }
    }
}
